// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowDisplay } from "./ThreadWorkflowDisplay";

export type ThreadSetNameParams = { threadId: string, name: string,
/**
 * Ephemeral, server-authoritative workflow context for the TUI footer.
 * Omit or set to `null` to clear the footer context, or provide a value to
 * replace it.
 */
workflowDisplay?: ThreadWorkflowDisplay, };
