// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadWorkflowDisplay = { workflow: string, phase?: string, task?: string, status?: string, completedTasks: bigint, totalTasks: bigint, progressPercent: number, };
